# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/lt02wifiue/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/lt02wifiue/proprietary/bin/mrvl_dut:system/bin/mrvl_dut \
    vendor/samsung/lt02wifiue/proprietary/bin/sensord:system/bin/sensord \
    vendor/samsung/lt02wifiue/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/lt02wifiue/proprietary/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/samsung/lt02wifiue/proprietary/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/samsung/lt02wifiue/proprietary/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libGLESv2SC.so:system/lib/libGLESv2SC.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libGAL.so:system/lib/libGAL.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/audio.primary.mrvl.so:system/lib/hw/audio.primary.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/audio_path.adda.mrvl.so:system/lib/hw/audio_path.adda.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/audio_path.fm.mrvl.so:system/lib/hw/audio_path.fm.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/audio_path.hifi.mrvl.so:system/lib/hw/audio_path.hifi.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/audio_path.vc.mrvl.so:system/lib/hw/audio_path.vc.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/audio_path.voip.mrvl.so:system/lib/hw/audio_path.voip.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/audio_path.vt.mrvl.so:system/lib/hw/audio_path.vt.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/audio_policy.mrvl.so:system/lib/hw/audio_policy.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/liblvvewrapper.so:system/lib/liblvvewrapper.so \
    vendor/samsung/lt02wifiue/proprietary/lib/liblvvefs.so:system/lib/liblvvefs.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libacoustic.so:system/lib/libacoustic.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libaudiodebugtool.so:system/lib/libaudiodebugtool.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/lt02wifiue/proprietary/lib/soundfx/libmrvlpreprocessing.so:system/lib/soundfx/libmrvlpreprocessing.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libmarvell-nvaccessor.so:system/lib/libmarvell-nvaccessor.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libMarvellWireless.so:system/lib/libMarvellWireless.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libMrvlOmx.so:system/lib/libMrvlOmx.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libnvaccessor.so:system/lib/libnvaccessor.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libmtelif.so:system/lib/libmtelif.so \
    vendor/samsung/lt02wifiue/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/lt02wifiue/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/camera.mrvl.so:system/lib/hw/camera.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libcameraengine.so:system/lib/libcameraengine.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libcodecjpegdec.so:system/lib/libcodecjpegdec.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libcodecjpegenc.so:system/lib/libcodecjpegenc.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libmiscgen.so:system/lib/libmiscgen.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libphycontmem.so:system/lib/libphycontmem.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libsocketsvr.so:system/lib/libsocketsvr.so \
    vendor/samsung/lt02wifiue/proprietary/etc/ov5647_scene_tuning.data:system/etc/ov5647_scene_tuning.data \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/sensors.mrvl.so:system/lib/hw/sensors.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/lt02wifiue/proprietary/etc/AGPS_CA.pem:system/etc/AGPS_CA.pem \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/csr.cpd.so:system/lib/hw/csr.cpd.so \
    vendor/samsung/lt02wifiue/proprietary/etc/firmware/mrvl/reg_alpha2:system/etc/firmware/mrvl/reg_alpha2 \
    vendor/samsung/lt02wifiue/proprietary/etc/firmware/mrvl/sd8787_uapsta.bin:system/etc/firmware/mrvl/sd8787_uapsta.bin \
    vendor/samsung/lt02wifiue/proprietary/etc/firmware/mrvl/txpwrlimit_cfg.conf:system/etc/firmware/mrvl/txpwrlimit_cfg.conf \
    vendor/samsung/lt02wifiue/proprietary/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin:system/etc/firmware/mrvl/w8787_wlan_SDIO_bt_SDIO.bin \
    vendor/samsung/lt02wifiue/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \
    vendor/samsung/lt02wifiue/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf_0:system/etc/firmware/mrvl/WlanCalData_ext.conf_0 \
    vendor/samsung/lt02wifiue/proprietary/lib/libwtpsp.so:system/lib/libwtpsp.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libwtpsp_ss.so:system/lib/libwtpsp_ss.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libwtpsp.so:system/lib/libwtpsp.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libwtpsp_ss.so:system/lib/libwtpsp_ss.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libsysfs.so:system/lib/libsysfs.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libsraxxd.so:system/lib/libsraxxd.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libsrvxxd.so:system/lib/libsrvxxd.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libsimal.so:system/lib/libsimal.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libserialport.so:system/lib/libserialport.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libceu.so:system/lib/libceu.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libCSP.so:system/lib/libCSP.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libgpucsc.so:system/lib/libgpucsc.so \
    vendor/samsung/lt02wifiue/proprietary/lib/lib_gsd5t_mode7.so:system/lib/lib_gsd5t_mode7.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libbz.so:system/lib/libbz.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libaah_rtp.so:system/lib/libaah_rtp.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libacm.so:system/lib/libacm.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libAndroidEvent.so:system/lib/libAndroidEvent.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libHSV.so:system/lib/libHSV.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libionhelper.so:system/lib/libionhelper.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libippimgp.so:system/lib/libippimgp.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libippsp.so:system/lib/libippsp.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libippvp.so:system/lib/libippvp.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libOrgan.so:system/lib/libOrgan.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libpmemhelper.so:system/lib/libpmemhelper.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libparseTim.so:system/lib/libparseTim.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libSDRMInvLH.so:system/lib/libSDRMInvLH.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/gralloc.mrvl.so:system/lib/hw/gralloc.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/hwcomposer.mrvl.so:system/lib/hw/hwcomposer.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/lt02wifiue/proprietary/lib/hw/lights.mrvl.so:system/lib/hw/lights.mrvl.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libdivxdrm.so:system/lib/libdivxdrm.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/lt02wifiue/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/lt02wifiue/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so
